# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnswersWindow(object):

    def setupUi(self, AnswersWindow):
        AnswersWindow.setObjectName("AnswersWindow")
        AnswersWindow.resize(1131, 872)
        AnswersWindow.setStyleSheet("background-color: rgb(255, 235, 225);\n"
                                    "")
        self.centralwidget = QtWidgets.QWidget(AnswersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 1111, 811))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1109, 809))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1110, 810))
        self.frame.setMinimumSize(QtCore.QSize(1110, 810))
        self.frame.setMaximumSize(QtCore.QSize(1000, 800))
        self.frame.setStyleSheet("background-color: rgb(255, 220, 199);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(310, 50, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
                                   "    background-color:rgb(163, 255, 123)\n"
                                   "}")
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame)
        self.listWidget_2.setGeometry(QtCore.QRect(80, 180, 950, 600))
        self.listWidget_2.setMinimumSize(QtCore.QSize(950, 600))
        self.listWidget_2.setMaximumSize(QtCore.QSize(950, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        # self.listWidget_2.setFont(font)
        # self.listWidget_2.setFlow(QtWidgets.QListView.TopToBottom)
        # self.listWidget_2.setResizeMode(QtWidgets.QListView.Adjust)
        # self.listWidget_2.setItemAlignment(QtCore.Qt.AlignCenter)
        # self.listWidget_2.setObjectName("listWidget_2")
        # item = QtWidgets.QListWidgetItem()
        # self.listWidget_2.addItem(item)


        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        AnswersWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnswersWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 26))
        self.menubar.setObjectName("menubar")
        AnswersWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnswersWindow)
        self.statusbar.setObjectName("statusbar")
        AnswersWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnswersWindow)
        QtCore.QMetaObject.connectSlotsByName(AnswersWindow)



    def retranslateUi(self, AnswersWindow):
        _translate = QtCore.QCoreApplication.translate
        AnswersWindow.setWindowTitle(_translate("AnswersWindow", "Quiz Answers"))
        self.label_7.setText(_translate("AnswersWindow", "QUIZ ANSWERS"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        # item = self.listWidget_2.item(0)
        # item.setText(_translate("AnswersWindow", "Comment 1 By User 1"))
        # self.listWidget_2.setSortingEnabled(__sortingEnabled)

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     AnswersWindow = QtWidgets.QMainWindow()
#     ui = Ui_AnswersWindow()
#     ui.setupUi(AnswersWindow)
#     AnswersWindow.show()
#     sys.exit(app.exec_())
